// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmah2IShDTs9wmUFyJ9RnG_E0eLds3xHo',
    appId: '1:371459689951:web:a1811b87d85d7308d8486a',
    messagingSenderId: '371459689951',
    projectId: 'bloodapp-56d72',
    authDomain: 'bloodapp-56d72.firebaseapp.com',
    storageBucket: 'bloodapp-56d72.appspot.com',
    measurementId: 'G-W0EBEHSLNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrh-Y8wsIcyNE_1I6N2fcnZceAp6HPeNs',
    appId: '1:371459689951:android:e96b1bca10336baed8486a',
    messagingSenderId: '371459689951',
    projectId: 'bloodapp-56d72',
    storageBucket: 'bloodapp-56d72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTyTnfMZH2YmgUgiRQswKt-Ne63RZpKos',
    appId: '1:371459689951:ios:7160df42b0cf0089d8486a',
    messagingSenderId: '371459689951',
    projectId: 'bloodapp-56d72',
    storageBucket: 'bloodapp-56d72.appspot.com',
    iosBundleId: 'com.example.bloodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmah2IShDTs9wmUFyJ9RnG_E0eLds3xHo',
    appId: '1:371459689951:web:58407e544fd4432ad8486a',
    messagingSenderId: '371459689951',
    projectId: 'bloodapp-56d72',
    authDomain: 'bloodapp-56d72.firebaseapp.com',
    storageBucket: 'bloodapp-56d72.appspot.com',
    measurementId: 'G-ZK1BS83VLS',
  );

}